### ISSUE TITLE
CircleCIとの連携する

### ISSUE THREAD

**Issue by johnsmith0951** [Montages-Team/MontageClient#19]
## 問題点
- [ ] 自動デプロイできない状況がある
- [ ] テストが通っていない状況でマージしたくない

## やることリスト
- [ ] docker composeにしたい。(起動コマンド等都合がいい)
- [ ] CircleCIの設定(テストの必要性ある?)
- [ ] Netlifyにデプロイ

**Comment by raguna2** [comment]
今の所困ってないのでクローズ
