### ISSUE TITLE
ヘッダーのログインボタンの処理を追加

### ISSUE THREAD

**Issue by raguna2** [Montages-Team/MontageClient#76]
## 概要
ヘッダーにAuthButtonコンポーネント(登録/ログインボタン)を追加し、
押したときにAuth0のログインページへ遷移するようにする

## コンポーネント名
AuthButton

## ファイル名
component/atom/AuthButton.vue

## コンポーネントを追加するファイル
component/organisms/Header.vue

## 実装内容
* ヘッダー内でisAuthentication=falseのときに表示する処理を書く
  * isAuthenticationの値はApp.vueから渡してくる必要あり
* AuthButtonを@clickしたときに`App.vue`内にある `login()`メソッドを起動させるようにする

## 要望
1. 一緒にヘッダーにあるロゴとボタンの位置をいい感じに修正してほしい

**Comment by johnsmith0951** [comment]
疎通確認

**Comment by johnsmith0951** [comment]
着手じゃな

**Comment by johnsmith0951** [comment]
疎通確認

**Comment by johnsmith0951** [comment]
Connection test
