### ISSUE TITLE
ヘッダーにメニューを追加

### ISSUE THREAD

**Issue by raguna2** [Montages-Team/MontageClient#78]
## 概要
ヘッダーに下記のようなメニューを追加する。このメニューはログイン時はユーザアイコンになり、ログインしていないときは今実装している通りの登録ログインボタンになる。

- ログインしてるとき
<img width="286" alt="スクリーンショット 0031-09-14 10 59 03" src="https://user-images.githubusercontent.com/10240512/64902293-90637900-d6df-11e9-91a8-a7d3008a15ee.png">

## 追加するコンポーネント名
- ProfileRoundImage.vue

## コンポーネントを追加するファイル
component/organisms/Header.vue

## 実装内容
* HeaderにProfileRoundImageを追加。
* ProfileRoundImageはisAuthenticated がTrueのとき表示させる。falseのときは登録ログインボタンのまま
* クリックしたときにメニューを表示させるがその実装は別isssue

**Comment by johnsmith0951** [comment]
いまログインしていないときヘッダー右側は「ログイン・登録」ボタンが表示されると思うけど、ハンバーガーメニューが表示されうのは設定面のときだけ？
Figma見たけど、ほかのどのページでハンバーガーメニュー使ってる？

**Comment by raguna2** [comment]
たしかにそうだわ。
この後 #84 を実装してもらおうと思っていたから一緒にやっちゃっていいかもしれない。(これだけだとスモールタスクすぎる気もするし)

他のページでもハンバーガ使ってないからなくしちゃってよさそう

**Comment by johnsmith0951** [comment]
マージしたので閉じ。
